Repository AndreRichartz/RailFlow-Refactored, pull requests merged in 2025-06, with the labels that each got.

#2 Create react.ts project
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/main.tsx
  src/pages/App.tsx
  src/styles/App.css
  src/styles/index.css
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: Feature

#4 3 create header component
  package-lock.json
  package.json
  src/components/Header.tsx
  src/components/Search.tsx
  src/styles/Header.component.css
  src/styles/Search.module.css
  src/styles/variables.css
Labels: Feature, Chore

#6 5 create app routes
  src/pages/App.tsx
  src/pages/Home.tsx
  src/pages/Inspection.tsx
  src/pages/NoticeBoard.tsx
  src/pages/ReportAndAnalisys.tsx
  src/pages/RouteManagement.tsx
  src/styles/App.css
Labels: Feature

#8 7 create header component
  src/components/Alert.tsx
  src/components/Header.tsx
  src/components/Option.tsx
  src/components/Status.tsx
  src/pages/Home.tsx
  src/styles/Alert.module.css
  src/styles/Header.module.css
  src/styles/Home.module.css
  src/styles/Options.module.css
  src/styles/Status.module.css
  src/styles/index.css
Labels: Feature

#10 Fix: Fixed header sticky property #9
  src/components/AlertCard.tsx
  src/components/Expand.tsx
  src/components/TitleNoticeBoard.tsx
  src/pages/Home.tsx
  src/pages/NoticeBoard.tsx
  src/styles/AlertCard.module.css
  src/styles/Expand.module.css
  src/styles/Home.module.css
  src/styles/NoticeBoard.module.css
  src/styles/TitleNoticeBoard.module.css
  src/styles/index.css
Labels: Fix

#14 feat: developed route management #13
  src/assets/img/10801642-vista-aerea-limpa-do-mapa-da-cidade-noturna-com-rua-e-rio-001-vetor.jpg
  src/assets/svg/menu-burger.svg
  src/assets/svg/search.svg
  src/assets/svg/train-icon.svg
  src/components/Header.tsx
  src/components/HorizontalSelection.tsx
  src/components/HorizontalSelectionCard.tsx
  src/components/Situation.tsx
  src/pages/Home.tsx
  src/pages/RouteManagement.tsx
  src/styles/Alert.module.css
  src/styles/Header.module.css
  src/styles/HorizontalSelection.module.css
  src/styles/HorizontalSelectionCard.module.css
  src/styles/InspectionCardInspection.module.css
  src/styles/InspectionCardMaintenance.module.css
  src/styles/Situation.module.css
  src/styles/index.css
Labels: Feature

#16 Feat: developed planning component #15
  src/components/Planning.tsx
  src/pages/RouteManagement.tsx
  src/styles/Planning.module.css
Labels: Feature
